Repository AmadeusITGroup/otter, pull requests merged in 2023-06, with the labels that each got.

#386 feat: setup verdaccio once for all it-tests
  .github/workflows/test-publish.yml
  .verdaccio/conf/.npmrc
  package.json
  packages/@o3r/core/schematics/index.it.spec.ts
Labels: enhancement

#359 feat: display the list of available Otter modules after ngAdd
  apps/vscode-extension/package.json
  apps/vscode-extension/src/commands/generate/component.command.ts
  apps/vscode-extension/src/commands/generate/fixture.command.ts
  apps/vscode-extension/src/commands/generate/module.command.ts
  apps/vscode-extension/src/commands/generate/service.command.ts
  apps/vscode-extension/src/commands/generate/store.command.ts
  apps/vscode-extension/src/commands/helpers.ts
  apps/vscode-extension/src/commands/module/add-module.command.ts
  apps/vscode-extension/src/extension.ts
  docs/core/MODULE.md
  packages/@o3r/analytics/README.md
  packages/@o3r/analytics/package.json
  packages/@o3r/apis-manager/package.json
  packages/@o3r/application/package.json
  packages/@o3r/components/package.json
  packages/@o3r/configuration/package.json
  packages/@o3r/core/collection.json
  packages/@o3r/core/schematics/module/index.ts
  packages/@o3r/core/schematics/module/schema.json
  packages/@o3r/core/schematics/module/templates/base/package.json.template
  packages/@o3r/core/schematics/module/templates/base/tsconfig.build.json.template
  packages/@o3r/core/schematics/module/templates/base/tsconfig.builders.json.template
  packages/@o3r/core/schematics/ng-add/index.ts
  packages/@o3r/core/schematics/ng-add/project-setup/index.ts
  packages/@o3r/core/schematics/rule-factories/module-list/index.ts
  packages/@o3r/core/schematics/show-modules/index.ts
  packages/@o3r/core/schematics/show-modules/schema.json
  packages/@o3r/core/schematics/show-modules/schema.ts
  packages/@o3r/core/src/modules/index.ts
  packages/@o3r/core/src/modules/module.constants.ts
  packages/@o3r/core/src/public_api.ts
  packages/@o3r/dev-tools/package.json
  packages/@o3r/dynamic-content/package.json
  packages/@o3r/eslint-config-otter/package.json
  packages/@o3r/eslint-plugin/package.json
  packages/@o3r/forms/package.json
  packages/@o3r/localization/README.md
  packages/@o3r/localization/package.json
  packages/@o3r/logger/package.json
  packages/@o3r/mobile/package.json
  packages/@o3r/routing/package.json
  packages/@o3r/rules-engine/README.md
  packages/@o3r/rules-engine/package.json
  packages/@o3r/schematics/package.json
  packages/@o3r/schematics/src/utility/collection.ts
  packages/@o3r/schematics/src/utility/modules.ts
  packages/@o3r/schematics/src/utility/package-version.ts
  packages/@o3r/store-sync/README.md
  packages/@o3r/store-sync/package.json
  packages/@o3r/storybook/package.json
  packages/@o3r/stylelint-plugin/package.json
  packages/@o3r/styling/README.md
  packages/@o3r/styling/package.json
  packages/@o3r/testing/README.md
  packages/@o3r/testing/package.json
  packages/@o3r/third-party/README.md
  packages/@o3r/third-party/package.json
  yarn.lock
Labels: documentation, enhancement

#387 fix: it-tests cache for yarn3
  .github/workflows/test-publish.yml
  packages/@o3r/core/schematics/index.it.spec.ts
Labels: bug

#385 feat: improve error logs format
  packages/@ama-sdk/core/src/fwk/clients/api-fetch-client.ts
  packages/@ama-sdk/core/src/fwk/errors.ts
  packages/@ama-sdk/core/src/plugins/core/reply-plugin.ts
  packages/@ama-sdk/core/src/plugins/exception/exception.reply.ts
Labels: enhancement

#398 feat: add vscode readonly file config
  .vscode/settings.json
  packages/@ama-sdk/generator-sdk/src/generators/shell/templates/base/package.json
Labels: enhancement

#410 fix: logo URL in npmjs
  packages/@o3r/analytics/README.md
  packages/@o3r/apis-manager/README.md
  packages/@o3r/application/README.md
  packages/@o3r/components/README.md
  packages/@o3r/configuration/README.md
  packages/@o3r/core/README.md
  packages/@o3r/dev-tools/README.md
  packages/@o3r/dynamic-content/README.md
  packages/@o3r/eslint-config-otter/README.md
  packages/@o3r/eslint-plugin/README.md
  packages/@o3r/extractors/README.md
  packages/@o3r/forms/README.md
  packages/@o3r/localization/README.md
  packages/@o3r/logger/README.md
  packages/@o3r/mobile/README.md
  packages/@o3r/routing/README.md
  packages/@o3r/rules-engine/README.md
  packages/@o3r/schematics/README.md
  packages/@o3r/storybook/README.md
  packages/@o3r/stylelint-plugin/README.md
  packages/@o3r/styling/README.md
  packages/@o3r/testing/README.md
  packages/@o3r/third-party/README.md
Labels: bug

#414 fix: add missing package.json in schematics build builder's output
  packages/@o3r/schematics/project.json
Labels: bug

#409 feat: add the support of `npm create @o3r`
  README.md
  docs/core/START_NEW_APPLICATION.md
  packages/@ama-sdk/schematics/project.json
  packages/@o3r/create/.eslintrc.js
  packages/@o3r/create/.gitignore
  packages/@o3r/create/.npmignore
  packages/@o3r/create/README.md
  packages/@o3r/create/package.json
  packages/@o3r/create/project.json
  packages/@o3r/create/src/index.ts
  packages/@o3r/create/tsconfig.build.json
  packages/@o3r/create/tsconfig.eslint.json
  packages/@o3r/create/tsconfig.json
  yarn.lock
Labels: documentation, enhancement

#395 feat: migrate cascading template to EJS
  apps/github-cascading-app/package.json
  apps/github-cascading-app/src/cascading/cascading-probot.ts
  apps/github-cascading-app/src/cascading/cascading.spec.ts
  apps/github-cascading-app/src/cascading/cascading.ts
  apps/github-cascading-app/src/cascading/interfaces.ts
  apps/github-cascading-app/src/cascading/templates/pull-request-content.ejs
  nx.json
  yarn.lock
Labels: enhancement

#416 feat: remove ama-sdk-schematics from publish
  package.json
  packages/@ama-sdk/generator-sdk/src/generators/shell/templates/base/package.json
Labels: enhancement

#407 fix: changed cascading origin branch
  apps/github-cascading-app/src/cascading/cascading.spec.ts
  apps/github-cascading-app/src/cascading/cascading.ts
Labels: bug

#419 fix: publish only latest cascading version
  .github/workflows/publish.yml
Labels: bug

#420 Cascading
  .github/workflows/publish.yml
  apps/github-cascading-app/src/cascading/cascading.spec.ts
  apps/github-cascading-app/src/cascading/cascading.ts
Labels: bug, cascading

#418 fix(cascading): missing runtime ejs dep
  apps/github-cascading-app/package.json
Labels: bug

#427 fix: correctly cache o3r/schematics schematics
  packages/@o3r/schematics/project.json
Labels: bug

#426 fix(chrome-extension): manifest version calculation
  apps/chrome-devtools/package.json
  apps/chrome-devtools/project.json
  apps/chrome-devtools/scripts/set-manifest-version.cjs
Labels: bug

#433 fix: ng-add core add dev dependencies from the lib
  packages/@ama-sdk/schematics/schematics/index.it.spec.ts
  packages/@o3r/core/schematics/index.it.spec.ts
  packages/@o3r/schematics/schematics/ng-add/index.ts
Labels: bug

#438 fix: add packages to it reproduce bundle
  .github/workflows/test-publish.yml
Labels: bug

#440 feat: add it test for rules-engine schematics
  packages/@ama-sdk/generator-sdk/src/generators/shell/templates/base/package.json
  packages/@ama-sdk/schematics/schematics/index.it.spec.ts
  packages/@o3r/core/package.json
  packages/@o3r/core/schematics/index.it.spec.ts
  packages/@o3r/rules-engine/jest.config.js
  packages/@o3r/rules-engine/package.json
  packages/@o3r/rules-engine/project.json
  packages/@o3r/rules-engine/schematics/index.it.spec.ts
  packages/@o3r/rules-engine/schematics/ng-add/index.ts
  packages/@o3r/rules-engine/testing/jest.config.it.js
  packages/@o3r/rules-engine/tsconfig.spec.json
  yarn.lock
Labels: enhancement

#431 schematics convert component ng to o3r
  packages/@ama-sdk/generator-sdk/src/schematics/mock/schema.ts
  packages/@o3r/components/schematics/iframe/schema.ts
  packages/@o3r/configuration/package.json
  packages/@o3r/core/README.md
  packages/@o3r/core/builders/app-version/schema.ts
  packages/@o3r/core/builders/ngc/schema.ts
  packages/@o3r/core/builders/pattern-replacement/schema.ts
  packages/@o3r/core/collection.json
  packages/@o3r/core/schematics/convert-component/index.spec.ts
  packages/@o3r/core/schematics/convert-component/index.ts
  packages/@o3r/core/schematics/convert-component/schema.json
  packages/@o3r/core/schematics/convert-component/schema.ts
  packages/@o3r/core/schematics/index.it.spec.ts
  packages/@o3r/core/schematics/page/schema.ts
  packages/@o3r/core/schematics/service/schema.ts
  packages/@o3r/core/schematics/store/common/schema.ts
  packages/@o3r/core/schematics/store/simple-sync/schema.ts
  packages/@o3r/localization/builders/i18n/schema.ts
  packages/@o3r/schematics/src/utility/component.ts
  yarn.lock
Labels: enhancement

#445 fix: check if configuration is already present
  packages/@o3r/configuration/schematics/configuration-to-component/index.spec.ts
  packages/@o3r/configuration/schematics/configuration-to-component/index.ts
Labels: bug

#451 fix(create): to be correctly run with node
  packages/@o3r/create/src/index.ts
Labels: bug

#456 fix(cascading): ignored -next branches
  .github/.cascadingrc.json
  apps/github-cascading-app/schemas/config.schema.json
  apps/github-cascading-app/src/cascading/cascading.spec.ts
  apps/github-cascading-app/src/cascading/cascading.ts
Labels: bug

#450 fix: base module downloading on schematic function
  packages/@ama-terasu/cli/package.json
  packages/@ama-terasu/cli/src/helpers/module.helper.ts
  packages/@o3r/schematics/src/modules/modules.helpers.ts
  yarn.lock
Labels: bug

#453 feat: split schematics component theming
  packages/@ama-sdk/generator-sdk/project.json
  packages/@ama-sdk/schematics/project.json
  packages/@o3r/configuration/schematics/ng-add/index.ts
  packages/@o3r/core/project.json
  packages/@o3r/core/schematics/component/common/configuration.ts
  packages/@o3r/core/schematics/component/common/theming.ts
  packages/@o3r/core/schematics/component/container/schema.json
  packages/@o3r/core/schematics/component/presenter/index.spec.ts
  packages/@o3r/core/schematics/component/presenter/index.ts
  packages/@o3r/core/schematics/component/presenter/schema.json
  packages/@o3r/core/schematics/component/presenter/schema.ts
  packages/@o3r/core/schematics/component/presenter/templates/presenter/__name__.style.scss
  packages/@o3r/core/schematics/component/schema.json
  packages/@o3r/core/schematics/component/schema.ts
  packages/@o3r/core/schematics/index.it.spec.ts
  packages/@o3r/core/schematics/rule-factories/otter-environment/index.ts
  packages/@o3r/schematics/src/rule-factories/ng-add/index.ts
  packages/@o3r/storybook/schematics/storybook-base/templates/__dot__storybook/styles/index.scss
  packages/@o3r/styling/collection.json
  packages/@o3r/styling/schematics/ng-add/index.ts
  packages/@o3r/styling/schematics/theming-to-component/index.spec.ts
  packages/@o3r/styling/schematics/theming-to-component/index.ts
  packages/@o3r/styling/schematics/theming-to-component/schema.json
  packages/@o3r/styling/schematics/theming-to-component/schema.ts
  packages/@o3r/styling/schematics/theming-to-component/templates/__name__.style.theme.scss
Labels: enhancement
