Repository AmadeusITGroup/otter, pull requests merged in 2023-07, with the labels that each got.

#464 feat: split schematics component localization
  packages/@ama-sdk/generator-sdk/src/generators/shell/templates/base/package.json
  packages/@o3r/configuration/README.md
  packages/@o3r/configuration/schematics/configuration-to-component/schema.json
  packages/@o3r/core/README.md
  packages/@o3r/core/schematics/component/common/localization.ts
  packages/@o3r/core/schematics/component/presenter/index.spec.ts
  packages/@o3r/core/schematics/component/presenter/index.ts
  packages/@o3r/core/schematics/component/presenter/schema.json
  packages/@o3r/core/schematics/component/presenter/templates/localization/__name__.localization.json
  packages/@o3r/core/schematics/component/presenter/templates/module/__name__.module.ts.template
  packages/@o3r/core/schematics/component/presenter/templates/presenter/__name__.component.ts.template
  packages/@o3r/core/schematics/component/presenter/templates/presenter/__name__.spec.ts.template
  packages/@o3r/core/schematics/component/presenter/templates/presenter/__name__.template.html
  packages/@o3r/core/schematics/component/schema.json
  packages/@o3r/core/schematics/index.it.spec.ts
  packages/@o3r/localization/README.md
  packages/@o3r/localization/collection.json
  packages/@o3r/localization/schematics/localization-to-component/index.spec.ts
  packages/@o3r/localization/schematics/localization-to-component/index.ts
  packages/@o3r/localization/schematics/localization-to-component/schema.json
  packages/@o3r/localization/schematics/localization-to-component/schema.ts
  packages/@o3r/localization/schematics/localization-to-component/templates/__name__.localization.json
  packages/@o3r/localization/schematics/localization-to-component/templates/__name__.translation.ts.template
  packages/@o3r/localization/testing/mocks/__dot__eslintrc.mocks.json
  packages/@o3r/localization/tsconfig.spec.json
  packages/@o3r/schematics/src/utility/component.ts
  packages/@o3r/styling/README.md
Labels: enhancement

#472 feat: split schematics component fixture
  packages/@o3r/configuration/schematics/configuration-to-component/index.ts
  packages/@o3r/core/schematics/component/common/fixture.ts
  packages/@o3r/core/schematics/component/container/index.spec.ts
  packages/@o3r/core/schematics/component/container/index.ts
  packages/@o3r/core/schematics/component/container/schema.json
  packages/@o3r/core/schematics/component/container/schema.ts
  packages/@o3r/core/schematics/component/container/templates/container/__name__.spec.ts.template
  packages/@o3r/core/schematics/component/presenter/index.spec.ts
  packages/@o3r/core/schematics/component/presenter/index.ts
  packages/@o3r/core/schematics/component/presenter/schema.json
  packages/@o3r/core/schematics/component/presenter/schema.ts
  packages/@o3r/core/schematics/component/presenter/templates/fixture/__name__.fixture.ts.template
  packages/@o3r/core/schematics/component/presenter/templates/presenter/__name__.spec.ts.template
  packages/@o3r/core/schematics/component/schema.json
  packages/@o3r/core/schematics/component/schema.ts
  packages/@o3r/localization/schematics/localization-to-component/index.ts
  packages/@o3r/testing/README.md
  packages/@o3r/testing/collection.json
  packages/@o3r/testing/package.json
  packages/@o3r/testing/schematics/fixture-to-component/index.spec.ts
  packages/@o3r/testing/schematics/fixture-to-component/index.ts
  packages/@o3r/testing/schematics/fixture-to-component/schema.json
  packages/@o3r/testing/schematics/fixture-to-component/schema.ts
  packages/@o3r/testing/schematics/fixture-to-component/templates/__name__.fixture.ts.template
  packages/@o3r/testing/testing/mocks/__dot__eslintrc.mocks.json
  yarn.lock
Labels: enhancement

#479 fix: angular-eslint version is decoupled from the angular one
  packages/@ama-sdk/schematics/schematics/typescript/shell/index.ts
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/package.json
Labels: bug

#463 fix: enforce style to SCSS in create command
  packages/@o3r/core/schematics/ng-add/index.ts
  packages/@o3r/create/.eslintrc.js
  packages/@o3r/create/package.json
  packages/@o3r/create/src/index.ts
  yarn.lock
Labels: bug

#476 feat: split schematics localization key
  packages/@o3r/localization/README.md
  packages/@o3r/localization/collection.json
  packages/@o3r/localization/schematics/add-localization-key/index.spec.ts
  packages/@o3r/localization/schematics/add-localization-key/index.ts
  packages/@o3r/localization/schematics/add-localization-key/schema.json
  packages/@o3r/localization/schematics/add-localization-key/schema.ts
  packages/@o3r/localization/schematics/localization-to-component/index.spec.ts
  packages/@o3r/localization/schematics/localization-to-component/index.ts
  packages/@o3r/localization/schematics/localization-to-component/templates/__name__.localization.json
  packages/@o3r/localization/schematics/localization-to-component/templates/__name__.translation.ts.template
Labels: enhancement

#482 feat: remove storybook schematics options
  apps/vscode-extension/package.json
  apps/vscode-extension/src/commands/generate/component.command.ts
  docs/README.md
  docs/core/START_NEW_APPLICATION.md
  docs/storybook/STORYBOOK.md
  packages/@o3r/core/README.md
  packages/@o3r/core/collection.json
  packages/@o3r/core/schematics/component/index.ts
  packages/@o3r/core/schematics/component/presenter/index.spec.ts
  packages/@o3r/core/schematics/component/presenter/index.ts
  packages/@o3r/core/schematics/component/presenter/schema.json
  packages/@o3r/core/schematics/component/presenter/schema.ts
  packages/@o3r/core/schematics/component/presenter/templates/storybook/__name__.stories.ts.template
  packages/@o3r/core/schematics/component/schema.json
  packages/@o3r/core/schematics/component/schema.ts
  packages/@o3r/core/schematics/rule-factories/otter-environment/index.ts
  packages/@o3r/core/schematics/storybook/index.spec.ts
  packages/@o3r/core/schematics/storybook/index.ts
  packages/@o3r/core/schematics/storybook/schema.json
  packages/@o3r/core/schematics/storybook/schema.ts
  packages/@o3r/schematics/src/interfaces/angular-workspace.ts
  packages/@o3r/storybook/README.md
Labels: enhancement

#484 fix: make o3r/localization optional dep in o3r/testing
  packages/@o3r/configuration/src/devkit/configuration-devtools.console.spec.ts
  packages/@o3r/testing/package.json
  packages/@o3r/testing/schematics/ng-update/v9-0/index.ts
  packages/@o3r/testing/schematics/ng-update/v9-0/localization-imports/localization-imports-map.ts
  packages/@o3r/testing/schematics/ng-update/v9-0/localization-imports/localization-imports.spec.ts
  packages/@o3r/testing/schematics/ng-update/v9-0/localization-imports/localization-imports.ts
  packages/@o3r/testing/schematics/ng-update/v9-0/localization-imports/mocks/angular.mocks.json.template
  packages/@o3r/testing/schematics/ng-update/v9-0/localization-imports/mocks/my-component-updated.ts.template
  packages/@o3r/testing/schematics/ng-update/v9-0/localization-imports/mocks/my-component.ts.template
  packages/@o3r/testing/src/public_api.ts
  yarn.lock
Labels: bug

#494 fix: re enable yarn audit
  .github/workflows/audit.yml
  packages/@ama-sdk/generator-sdk/src/generators/shell/templates/base/package.json
  packages/@o3r/analytics/package.json
  packages/@o3r/configuration/package.json
  packages/@o3r/core/package.json
  packages/@o3r/dev-tools/.gitignore
  packages/@o3r/dev-tools/package.json
  packages/@o3r/dynamic-content/package.json
  packages/@o3r/routing/package.json
  packages/@o3r/rules-engine/package.json
  yarn.lock
Labels: bug

#496 feat: split schematics component refactor
  .vscode/extensions.json
  apps/vscode-extension/src/commands/generate/fixture.command.ts
  packages/@o3r/analytics/schematics/analytics-to-component/index.spec.ts
  packages/@o3r/analytics/schematics/analytics-to-component/index.ts
  packages/@o3r/analytics/schematics/analytics-to-component/schema.json
  packages/@o3r/configuration/schematics/configuration-to-component/index.spec.ts
  packages/@o3r/configuration/schematics/configuration-to-component/index.ts
  packages/@o3r/core/README.md
  packages/@o3r/core/collection.json
  packages/@o3r/core/schematics/component/common/analytics.ts
  packages/@o3r/core/schematics/component/common/common.ts
  packages/@o3r/core/schematics/component/common/configuration.ts
  packages/@o3r/core/schematics/component/common/context.ts
  packages/@o3r/core/schematics/component/common/fixture.ts
  packages/@o3r/core/schematics/component/common/localization.ts
  packages/@o3r/core/schematics/component/common/theming.ts
  packages/@o3r/core/schematics/component/presenter/schema.json
  packages/@o3r/core/schematics/component/schema.json
  packages/@o3r/core/schematics/component/schema.ts
  packages/@o3r/core/schematics/context-to-component/index.ts
  packages/@o3r/localization/schematics/add-localization-key/index.spec.ts
  packages/@o3r/localization/schematics/add-localization-key/index.ts
  packages/@o3r/localization/schematics/localization-to-component/index.spec.ts
  packages/@o3r/localization/schematics/localization-to-component/index.ts
  packages/@o3r/localization/schematics/localization-to-component/schema.json
  packages/@o3r/localization/schematics/localization-to-component/schema.ts
  packages/@o3r/schematics/src/rule-factories/add-imports/index.ts
  packages/@o3r/schematics/src/rule-factories/index.ts
  packages/@o3r/schematics/src/utility/ast.ts
  packages/@o3r/schematics/src/utility/component.ts
  packages/@o3r/styling/schematics/theming-to-component/index.ts
  packages/@o3r/testing/README.md
  packages/@o3r/testing/collection.json
  packages/@o3r/testing/schematics/add-functions-to-fixture/helpers.ts
  packages/@o3r/testing/schematics/add-functions-to-fixture/index.spec.ts
  packages/@o3r/testing/schematics/add-functions-to-fixture/index.ts
  packages/@o3r/testing/schematics/add-functions-to-fixture/mocks/example-empty.fixture.ts.mock
  packages/@o3r/testing/schematics/add-functions-to-fixture/mocks/example.fixture.ts.mock
  packages/@o3r/testing/schematics/add-functions-to-fixture/models.ts
  packages/@o3r/testing/schematics/add-functions-to-fixture/schema.json
  packages/@o3r/testing/schematics/add-functions-to-fixture/schema.ts
  packages/@o3r/testing/schematics/fixture-to-component/index.spec.ts
  packages/@o3r/testing/schematics/fixture-to-component/index.ts
Labels: enhancement

#485 fix: update ng add @ama-sdk/schematics to update swagger-ignore file
  packages/@ama-sdk/schematics/package.json
  packages/@ama-sdk/schematics/schematics/ng-add/index.ts
  packages/@ama-sdk/schematics/schematics/typescript/shell/index.spec.ts
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/.gitignore
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/.openapi-generator-ignore
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/openapitools.json
  packages/@o3r/schematics/package.json
  yarn.lock
Labels: bug

#503 refactor: breaking-change: modification of the schema for styling extractor
  packages/@o3r/core/package.json
  packages/@o3r/storybook/src/styling/styling.helpers.ts
  packages/@o3r/storybook/src/styling/styling.spec.ts
  packages/@o3r/styling/builders/style-extractor/helpers/css-variable.extractor.ts
  packages/@o3r/styling/builders/style-extractor/index.ts
  packages/@o3r/styling/schemas/style.metadata.schema.json
  packages/@o3r/styling/src/core/styles.interface.ts
Labels: breaking change

#461 feat: schematics to add rules-engine on a component
  packages/@o3r/core/schematics/component/common/rules-engine.ts
  packages/@o3r/core/schematics/component/container/index.spec.ts
  packages/@o3r/core/schematics/component/container/index.ts
  packages/@o3r/core/schematics/component/container/schema.json
  packages/@o3r/core/schematics/component/container/schema.ts
  packages/@o3r/core/schematics/component/index.ts
  packages/@o3r/core/schematics/component/schema.json
  packages/@o3r/core/schematics/component/schema.ts
  packages/@o3r/core/schematics/index.it.spec.ts
  packages/@o3r/rules-engine/README.md
  packages/@o3r/rules-engine/collection.json
  packages/@o3r/rules-engine/package.json
  packages/@o3r/rules-engine/schematics/index.it.spec.ts
  packages/@o3r/rules-engine/schematics/ng-add/index.ts
  packages/@o3r/rules-engine/schematics/rules-engine-to-component/index.spec.ts
  packages/@o3r/rules-engine/schematics/rules-engine-to-component/index.ts
  packages/@o3r/rules-engine/schematics/rules-engine-to-component/schema.json
  packages/@o3r/rules-engine/schematics/rules-engine-to-component/schema.ts
  packages/@o3r/rules-engine/testing/mocks/__dot__eslintrc.mocks.json
  packages/@o3r/schematics/src/utility/ast.ts
  yarn.lock
Labels: enhancement

#505 fix: add version cleaning on set-version command
  packages/@o3r/dev-tools/src/cli/set-version.ts
Labels: bug

#511 fix: export assets-path-override store module
  packages/@o3r/dynamic-content/src/stores/index.ts
Labels: bug

#510 Update README.mustache
  packages/@ama-sdk/schematics/schematics/java/client-core/swagger-codegen-java-client/src/main/resources/javaClient/README.mustache
Labels: documentation

#516 fix(cascading): create pull request from the correct branch
  apps/github-cascading-app/src/cascading/cascading.ts
Labels: bug

#518 fix: add Nx In Angular upgrade PR
  .renovaterc.json
Labels: bug

#504 fix: ng-add @ama-sdk/schematics and override tree
  packages/@ama-sdk/schematics/schematics/code-generator/code-generator.ts
  packages/@ama-sdk/schematics/schematics/code-generator/open-api-cli-generator/open-api-cli.options.ts
  packages/@ama-sdk/schematics/schematics/code-generator/swagger-java-generator/swagger-java.options.ts
  packages/@ama-sdk/schematics/schematics/java/client-core/index.ts
  packages/@ama-sdk/schematics/schematics/java/client-core/schema.json
  packages/@ama-sdk/schematics/schematics/java/client-core/schema.ts
  packages/@ama-sdk/schematics/schematics/ng-add/index.ts
  packages/@ama-sdk/schematics/schematics/typescript/core/index.ts
  packages/@ama-sdk/schematics/schematics/typescript/core/schema.json
  packages/@ama-sdk/schematics/schematics/typescript/core/schema.ts
Labels: bug

#275 feat: add documentation on placeholder dynamic documentation
  docs/components/PLACEHOLDERS.md
  docs/rules-engine/how-to-use/placeholders.md
Labels: documentation, enhancement

#525 fix(ama-sdk/create): enable create feature for yarn pnp
  packages/@ama-sdk/create/README.md
  packages/@ama-sdk/create/project.json
  packages/@ama-sdk/create/src/index.it.spec.ts
  packages/@ama-sdk/create/src/index.ts
  packages/@ama-sdk/schematics/project.json
  packages/@ama-sdk/schematics/schematics/index.it.spec.ts
Labels: bug

#434 feat: add ng-add preset feature
  .github/workflows/test-publish.yml
  packages/@ama-sdk/schematics/schematics/helpers/node-install.ts
  packages/@ama-sdk/schematics/schematics/typescript/shell/index.spec.ts
  packages/@o3r/components/schematics/ng-add/schema.json
  packages/@o3r/configuration/schematics/ng-add/schema.json
  packages/@o3r/core/ng-package.json
  packages/@o3r/core/package.json
  packages/@o3r/core/schematics/add-modules/index.ts
  packages/@o3r/core/schematics/add-modules/schema.json
  packages/@o3r/core/schematics/add-modules/schema.ts
  packages/@o3r/core/schematics/component/common/common.ts
  packages/@o3r/core/schematics/index.it.spec.ts
  packages/@o3r/core/schematics/ng-add/index.ts
  packages/@o3r/core/schematics/ng-add/presets/basic.preset.ts
  packages/@o3r/core/schematics/ng-add/presets/cms.preset.ts
  packages/@o3r/core/schematics/ng-add/presets/helpers.ts
  packages/@o3r/core/schematics/ng-add/presets/index.ts
  packages/@o3r/core/schematics/ng-add/presets/preset.interface.ts
  packages/@o3r/core/schematics/ng-add/project-setup/index.ts
  packages/@o3r/core/schematics/ng-add/schema.json
  packages/@o3r/core/schematics/ng-add/schema.ts
  packages/@o3r/dynamic-content/schematics/ng-add/schema.json
  packages/@o3r/localization/schematics/localization-base/index.ts
  packages/@o3r/localization/schematics/ng-add/schema.json
  packages/@o3r/rules-engine/package.json
  packages/@o3r/rules-engine/schematics/index.it.spec.ts
  packages/@o3r/rules-engine/schematics/ng-add/schema.json
  packages/@o3r/schematics/schematics/ng-add/index.ts
  packages/@o3r/schematics/src/interfaces/angular-workspace.ts
  packages/@o3r/schematics/src/rule-factories/ng-add/index.ts
  packages/@o3r/schematics/src/tasks/index.ts
  packages/@o3r/schematics/src/tasks/package-manager/add-dev-dependency.ts
  packages/@o3r/schematics/src/tasks/package-manager/index.ts
  packages/@o3r/schematics/src/tasks/package-manager/interfaces.ts
  packages/@o3r/schematics/src/tasks/package-manager/npm-install.ts
  packages/@o3r/schematics/tsconfig.builders.json
  packages/@o3r/styling/schematics/ng-add/schema.json
  yarn.lock
Labels: enhancement

#539 Cherry pick from main - fix(ama-sdk/create): enable create feature for yarn pnp
  packages/@ama-sdk/create/README.md
  packages/@ama-sdk/create/project.json
  packages/@ama-sdk/create/src/index.it.spec.ts
  packages/@ama-sdk/create/src/index.ts
  packages/@ama-sdk/schematics/project.json
  packages/@ama-sdk/schematics/schematics/index.it.spec.ts
Labels: bug

#544 fix: sdk generator - enhance questions for typescript shell
  packages/@ama-sdk/schematics/schematics/typescript/shell/schema.json
  packages/@ama-sdk/schematics/schematics/typescript/shell/schema.ts
Labels: bug

#536 fix: default value in schematics schema.json (for NX support)
  packages/@ama-sdk/schematics/schematics/java/client-core/index.ts
  packages/@ama-sdk/schematics/schematics/java/client-core/schema.json
  packages/@ama-sdk/schematics/schematics/java/client-core/schema.ts
  packages/@ama-sdk/schematics/schematics/typescript/core/schema.json
  packages/@ama-sdk/schematics/schematics/typescript/core/schema.ts
  packages/@ama-sdk/schematics/schematics/typescript/shell/schema.json
  packages/@ama-sdk/schematics/schematics/typescript/shell/schema.ts
  packages/@o3r/components/builders/component-extractor/schema.json
  packages/@o3r/components/builders/component-extractor/schema.ts
  packages/@o3r/core/builders/ngc/schema.json
  packages/@o3r/core/builders/pattern-replacement/schema.json
  packages/@o3r/core/schematics/module/schema.json
  packages/@o3r/core/schematics/module/schema.ts
  packages/@o3r/core/schematics/page/schema.json
  packages/@o3r/localization/builders/localization/schema.json
  packages/@o3r/localization/schematics/add-localization-key/schema.json
  packages/@o3r/localization/schematics/add-localization-key/schema.ts
  packages/@o3r/localization/schematics/localization-to-component/schema.json
  packages/@o3r/localization/schematics/localization-to-component/schema.ts
  packages/@o3r/testing/schematics/fixture-to-component/schema.json
  packages/@o3r/testing/schematics/fixture-to-component/schema.ts
Labels: bug

#547 fix(cascading): increase get branch limit
  apps/github-cascading-app/src/cascading/cascading-probot.ts
Labels: bug

#542 fix(component): configuration extractor to extract aliased types
  packages/@o3r/components/builders/component-extractor/helpers/component/component-config.extractor.ts
Labels: bug

#549 fix(ama-sdk/core): origin variable definition to error reporting
  packages/@ama-sdk/core/src/fwk/clients/api-fetch-client.ts
Labels: bug

#532 fix: sdk generator - support native return types
  packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/api/api.mustache
Labels: bug

#548 feat(cascading): add support for multi repositories with more than 10…
  apps/github-cascading-app/src/cascading/cascading-probot.ts
  apps/github-cascading-app/src/cascading/cascading.ts
Labels: enhancement

#538 fix: remove eslint installed by default
  packages/@o3r/schematics/schematics/ng-add/index.ts
Labels: bug

#558 feat: add schematic option to select o3r component type
  packages/@o3r/core/schematics/convert-component/index.spec.ts
  packages/@o3r/core/schematics/convert-component/index.ts
  packages/@o3r/core/schematics/convert-component/schema.json
  packages/@o3r/core/schematics/convert-component/schema.ts
Labels: enhancement

#500 feat: use angular schematic to generate component
  packages/@o3r/core/schematics/component/container/index.spec.ts
  packages/@o3r/core/schematics/component/container/index.ts
  packages/@o3r/core/schematics/component/container/templates/README.md
  packages/@o3r/core/schematics/component/container/templates/container/__name__.component.ts.template
  packages/@o3r/core/schematics/component/container/templates/container/__name__.spec.ts.template
  packages/@o3r/core/schematics/component/container/templates/container/__name__.template.html
  packages/@o3r/core/schematics/component/container/templates/index.ts.template
  packages/@o3r/core/schematics/component/container/templates/module/__name__.module.ts.template
  packages/@o3r/core/schematics/component/index.ts
  packages/@o3r/core/schematics/component/presenter/index.spec.ts
  packages/@o3r/core/schematics/component/presenter/index.ts
  packages/@o3r/core/schematics/component/presenter/templates/README.md
  packages/@o3r/core/schematics/component/presenter/templates/index.ts.template
  packages/@o3r/core/schematics/component/presenter/templates/module/__name__.module.ts.template
  packages/@o3r/core/schematics/component/presenter/templates/presenter/__name__.component.ts.template
  packages/@o3r/core/schematics/component/presenter/templates/presenter/__name__.spec.ts.template
  packages/@o3r/core/schematics/component/presenter/templates/presenter/__name__.style.scss
  packages/@o3r/core/schematics/component/presenter/templates/presenter/__name__.template.html
  packages/@o3r/core/schematics/ng-add/index.ts
  packages/@o3r/core/schematics/ng-add/schema.json
  packages/@o3r/core/schematics/ng-add/schema.ts
  packages/@o3r/core/schematics/rule-factories/otter-environment/index.ts
  packages/@o3r/localization/schematics/localization-to-component/index.ts
  packages/@o3r/schematics/src/utility/ast.ts
  packages/@o3r/schematics/src/utility/component.ts
  packages/@o3r/styling/schematics/theming-to-component/index.ts
Labels: enhancement

#555 feat: schematics to add iframe to a component
  packages/@o3r/components/collection.json
  packages/@o3r/components/schematics/iframe/index.spec.ts
  packages/@o3r/components/schematics/iframe/index.ts
  packages/@o3r/components/schematics/iframe/schema.json
  packages/@o3r/components/schematics/iframe/schema.ts
  packages/@o3r/components/schematics/iframe/templates/config/__name__.config.ts.template
  packages/@o3r/components/schematics/iframe/templates/iframe/README.md
  packages/@o3r/components/schematics/iframe/templates/iframe/__name__.component.ts.template
  packages/@o3r/components/schematics/iframe/templates/iframe/__name__.spec.ts.template
  packages/@o3r/components/schematics/iframe/templates/iframe/__name__.template.html
  packages/@o3r/components/schematics/iframe/templates/iframe/index.ts
  packages/@o3r/components/schematics/iframe/templates/module/__name__.module.ts.template
  packages/@o3r/third-party/.eslintrc.js
  packages/@o3r/third-party/README.md
  packages/@o3r/third-party/collection.json
  packages/@o3r/third-party/package.json
  packages/@o3r/third-party/schematics/iframe-to-component/index.spec.ts
  packages/@o3r/third-party/schematics/iframe-to-component/index.ts
  packages/@o3r/third-party/schematics/iframe-to-component/schema.json
  packages/@o3r/third-party/schematics/iframe-to-component/schema.ts
  packages/@o3r/third-party/schematics/ng-add/index.ts
  packages/@o3r/third-party/testing/mocks/__dot__eslintrc.mocks.json
  packages/@o3r/third-party/tsconfig.spec.json
  yarn.lock
Labels: enhancement

#559 feat: add async support to preset feature
  packages/@o3r/core/schematics/add-modules/index.ts
  packages/@o3r/core/schematics/library/rules/rules.nx.ts
  packages/@o3r/core/schematics/ng-add/index.ts
  packages/@o3r/core/schematics/rule-factories/module-list/index.ts
  packages/@o3r/core/schematics/shared/presets/basic.preset.ts
  packages/@o3r/core/schematics/shared/presets/cms.preset.ts
  packages/@o3r/core/schematics/shared/presets/helpers.ts
  packages/@o3r/core/schematics/shared/presets/preset.interface.ts
  packages/@o3r/schematics/src/modules/modules.helpers.ts
  packages/@o3r/schematics/src/utility/package-manager-runner.ts
Labels: enhancement

#564 fix(cascading): the way to cancel re-trigger of cascading
  apps/github-cascading-app/src/cascading/cascading.spec.ts
  apps/github-cascading-app/src/cascading/cascading.ts
  apps/github-cascading-app/src/cascading/templates/pull-request-content.ejs
Labels: bug

#560 feat: use angular schematic to generate page
  packages/@o3r/core/schematics/component/container/index.ts
  packages/@o3r/core/schematics/component/presenter/index.ts
  packages/@o3r/core/schematics/component/schema.json
  packages/@o3r/core/schematics/page/index.spec.ts
  packages/@o3r/core/schematics/page/index.ts
  packages/@o3r/core/schematics/page/schema.json
  packages/@o3r/core/schematics/page/schema.ts
  packages/@o3r/core/schematics/page/templates/README.md
  packages/@o3r/core/schematics/page/templates/config/__name@dasherize__.config.ts.template
  packages/@o3r/core/schematics/page/templates/index.ts.template
  packages/@o3r/core/schematics/page/templates/localization/__name@dasherize__.localization.json
  packages/@o3r/core/schematics/page/templates/localization/__name@dasherize__.translation.ts.template
  packages/@o3r/core/schematics/page/templates/module/__name@dasherize__.module.ts.template
  packages/@o3r/core/schematics/page/templates/page/README.md
  packages/@o3r/core/schematics/page/templates/page/__name@dasherize__.component.ts.template
  packages/@o3r/core/schematics/page/templates/page/__name@dasherize__.fixture.ts.template
  packages/@o3r/core/schematics/page/templates/page/__name@dasherize__.resolver.ts.template
  packages/@o3r/core/schematics/page/templates/page/__name@dasherize__.spec.ts.template
  packages/@o3r/core/schematics/page/templates/page/__name@dasherize__.style.scss
  packages/@o3r/core/schematics/page/templates/page/__name@dasherize__.template.html
  packages/@o3r/core/schematics/page/templates/theming/__name@dasherize__.style.theme.scss
  packages/@o3r/core/schematics/rule-factories/component/analytics.ts
  packages/@o3r/core/schematics/rule-factories/component/common.ts
  packages/@o3r/core/schematics/rule-factories/component/configuration.ts
  packages/@o3r/core/schematics/rule-factories/component/context.ts
  packages/@o3r/core/schematics/rule-factories/component/fixture.ts
  packages/@o3r/core/schematics/rule-factories/component/localization.ts
  packages/@o3r/core/schematics/rule-factories/component/rules-engine.ts
  packages/@o3r/core/schematics/rule-factories/component/theming.ts
  packages/@o3r/testing/schematics/fixture-to-component/schema.json
  packages/@o3r/testing/schematics/fixture-to-component/schema.ts
  packages/@o3r/testing/schematics/fixture-to-component/templates/__name__.fixture.ts.template
Labels: enhancement

#568 fix: remove duplicated preset files
  packages/@o3r/core/schematics/ng-add/presets/basic.preset.ts
  packages/@o3r/core/schematics/ng-add/presets/cms.preset.ts
  packages/@o3r/core/schematics/ng-add/presets/helpers.ts
  packages/@o3r/core/schematics/ng-add/presets/index.ts
  packages/@o3r/core/schematics/ng-add/presets/preset.interface.ts
Labels: bug

#573 fix(schematics): url to target registry search api
  packages/@o3r/schematics/src/modules/modules.helpers.ts
  packages/@o3r/schematics/src/utility/package-manager-runner.ts
Labels: bug

#530 fix: support debug for sdk generator and add doc
  packages/@ama-sdk/schematics/README.md
  packages/@ama-sdk/schematics/schematics/code-generator/open-api-cli-generator/open-api-cli.generator.ts
  packages/@ama-sdk/schematics/schematics/code-generator/open-api-cli-generator/open-api-cli.options.ts
  packages/@ama-sdk/schematics/schematics/typescript/core/index.ts
  packages/@ama-sdk/schematics/schematics/typescript/core/schema.json
  packages/@ama-sdk/schematics/schematics/typescript/core/schema.ts
Labels: bug, documentation

#575 fix: fixtures generation
  packages/@o3r/testing/schematics/add-functions-to-fixture/helpers.ts
  packages/@o3r/testing/schematics/fixture-to-component/index.spec.ts
  packages/@o3r/testing/schematics/fixture-to-component/index.ts
Labels: bug

#572 feat: add playwright postinstall cache
  apps/chrome-devtools/package.json
  package.json
  packages/@ama-sdk/core/package.json
  packages/@ama-sdk/create/package.json
  packages/@ama-sdk/generator-sdk/package.json
  packages/@ama-sdk/generator-sdk/src/generators/shell/templates/base/package.json
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/package.json.template
  packages/@o3r/create/package.json
  packages/@o3r/dev-tools/package.json
  packages/@o3r/eslint-plugin/package.json
  packages/@o3r/extractors/package.json
  packages/@o3r/rules-engine/package.json
  packages/@o3r/storybook/package.json
  packages/@o3r/stylelint-plugin/package.json
  packages/@o3r/third-party/package.json
  tools/github-actions/setup/action.yml
  tsconfig.base.json
  yarn.lock
Labels: enhancement

#529 fix: sdk generator - date support and doc
  packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/java/com/amadeus/codegen/ts/AbstractTypeScriptClientCodegen.java
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/readme.md
Labels: bug, documentation

#570 fix: export AssetPathOverrideStoreModule to allow path override in ap…
  packages/@o3r/dynamic-content/src/stores/asset-path-override/index.ts
  packages/@o3r/dynamic-content/src/stores/index.ts
Labels: bug

#579 feat: improve metadata extraction warning message
  packages/@o3r/components/builders/component-extractor/helpers/component/component.extractor.ts
Labels: enhancement

#581 feat: generate package.json files for builders and schematics
  nx.json
  packages/@ama-sdk/core/package.json
  packages/@ama-sdk/schematics/package.json
  packages/@o3r/analytics/package.json
  packages/@o3r/apis-manager/package.json
  packages/@o3r/application/package.json
  packages/@o3r/components/package.json
  packages/@o3r/configuration/package.json
  packages/@o3r/core/package.json
  packages/@o3r/core/schematics/ng-add/index.ts
  packages/@o3r/dev-tools/package.json
  packages/@o3r/dynamic-content/package.json
  packages/@o3r/eslint-config-otter/package.json
  packages/@o3r/eslint-plugin/package.json
  packages/@o3r/extractors/package.json
  packages/@o3r/forms/package.json
  packages/@o3r/localization/package.json
  packages/@o3r/logger/package.json
  packages/@o3r/mobile/package.json
  packages/@o3r/routing/package.json
  packages/@o3r/rules-engine/package.json
  packages/@o3r/schematics/package.json
  packages/@o3r/schematics/src/utility/index.ts
  packages/@o3r/schematics/src/utility/logo.ts
  packages/@o3r/store-sync/package.json
  packages/@o3r/storybook/package.json
  packages/@o3r/styling/package.json
  packages/@o3r/testing/package.json
  packages/@o3r/third-party/package.json
  tools/@o3r/build-helpers/package.json
  tools/@o3r/build-helpers/scripts/generate-cjs-manifest.mjs
  tools/@o3r/build-helpers/tsconfig.eslint.json
  yarn.lock
Labels: enhancement

#541 fix: sdk generator - support npm as package manager in templates
  packages/@ama-sdk/schematics/schematics/typescript/shell/index.spec.ts
  packages/@ama-sdk/schematics/schematics/typescript/shell/index.ts
  packages/@ama-sdk/schematics/schematics/typescript/shell/schema.json
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/.gitignore.template
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/.husky/commit-msg
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/.husky/pre-commit
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/.renovaterc.json
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/.vscode/settings.json
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/package.json.template
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/readme.md
Labels: bug

#584 feat: #583: exclude only incompatible properties and not the full config
  packages/@o3r/components/builders/component-extractor/helpers/component/component.extractor.ts
  packages/@o3r/components/builders/component-extractor/index.ts
Labels: enhancement

#585 fix: support multiple type depending on the reponse code
  packages/@ama-sdk/core/src/fwk/clients/api-fetch-client.ts
  packages/@ama-sdk/core/src/fwk/core/api-client.ts
  packages/@ama-sdk/schematics/schematics/typescript/core/index.spec.ts
  packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/java/com/amadeus/codegen/ts/AbstractTypeScriptClientCodegen.java
  packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/api/api.mustache
  packages/@ama-sdk/schematics/testing/MOCK_swagger.yaml
Labels: bug

#531 fix: carret on peer dep and remove useless dep
  packages/@ama-sdk/core/package.json
  packages/@ama-sdk/schematics/package.json
  packages/@o3r/dev-tools/src/cli/version-harmonize.ts
  yarn.lock
Labels: bug

#589 fix: match the fixture signature to the api endpoint in case of multi…
  packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/api/fixture.jest.mustache
Labels: bug

#592 fix: do not export empty type on index with models
  packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/model/index.mustache
Labels: bug

#566 feat: remove comment-json in schematics
  .husky/pre-commit
  .vscode/settings.json
  packages/@o3r/analytics/package.json
  packages/@o3r/apis-manager/package.json
  packages/@o3r/apis-manager/schematics/helpers/update-api-deps/index.ts
  packages/@o3r/application/package.json
  packages/@o3r/application/schematics/ng-add/index.ts
  packages/@o3r/core/builders/ngc/index.ts
  packages/@o3r/core/ng-package.json
  packages/@o3r/core/package.json
  packages/@o3r/core/schematics/ng-add/updates-for-v8/cms-adapters/update-builders-names.ts
  packages/@o3r/core/schematics/ng-add/updates-for-v8/generators/update-generators-names.ts
  packages/@o3r/core/schematics/ng-update/v4.3/playwright-update.ts
  packages/@o3r/core/schematics/ng-update/v4/api-services/index.ts
  packages/@o3r/core/schematics/ng-update/v4/store-actions/index.ts
  packages/@o3r/core/schematics/ng-update/v4/sub-entries/index.ts
  packages/@o3r/core/schematics/ng-update/v6.1/use-ngx-prefetch.ts
  packages/@o3r/core/schematics/ng-update/v6/update-angular-json.ts
  packages/@o3r/core/schematics/rule-factories/additional-modules/index.ts
  packages/@o3r/core/schematics/rule-factories/cms-adapter/index.ts
  packages/@o3r/core/schematics/rule-factories/fixture/index.ts
  packages/@o3r/core/schematics/rule-factories/otter-environment/index.ts
  packages/@o3r/core/schematics/rule-factories/store/index.ts
  packages/@o3r/core/schematics/scripts/exported-actions.ts
  packages/@o3r/core/schematics/scripts/sub-entry-imports.ts
  packages/@o3r/core/schematics/store-action/index.ts
  packages/@o3r/dev-tools/package.json
  packages/@o3r/dev-tools/src/cli/checks/in-source-dep-check.ts
  packages/@o3r/dev-tools/src/utils/package-manager.ts
  packages/@o3r/eslint-config-otter/package.json
  packages/@o3r/eslint-config-otter/schematics/ng-add/linter/index.ts
  packages/@o3r/localization/schematics/localization-base/index.ts
  packages/@o3r/rules-engine/package.json
  packages/@o3r/schematics/package.json
  packages/@o3r/schematics/schematics/ng-add/index.ts
  packages/@o3r/schematics/src/rule-factories/check-packages-peers/index.ts
  packages/@o3r/schematics/src/utility/ast.ts
  packages/@o3r/schematics/src/utility/file-info.ts
  packages/@o3r/schematics/src/utility/loaders.ts
  packages/@o3r/schematics/src/utility/modules.ts
  packages/@o3r/schematics/src/utility/package-manager-runner.ts
  packages/@o3r/schematics/src/utility/routes.ts
  packages/@o3r/storybook/package.json
  packages/@o3r/storybook/schematics/storybook-base/index.ts
  packages/@o3r/testing/package.json
  packages/@o3r/testing/schematics/add-functions-to-fixture/index.ts
  packages/@o3r/testing/schematics/playwright/sanity/index.spec.ts
  packages/@o3r/testing/schematics/playwright/scenario/index.spec.ts
  yarn.lock
Labels: enhancement

#509 feat: include cms-adapter when adding @o3r/localization
  packages/@o3r/components/package.json
  packages/@o3r/components/schematics/cms-adapter/index.ts
  packages/@o3r/components/schematics/ng-add/index.ts
  packages/@o3r/components/schematics/ng-add/schema.json
  packages/@o3r/components/schematics/ng-add/schema.ts
  packages/@o3r/core/schematics/index.it.spec.ts
  packages/@o3r/core/schematics/ng-add/project-setup/index.ts
  packages/@o3r/core/schematics/rule-factories/cms-adapter/index.ts
  packages/@o3r/core/schematics/rule-factories/index.ts
  packages/@o3r/core/schematics/shared/presets/helpers.ts
  packages/@o3r/extractors/package.json
  packages/@o3r/extractors/schematics/cms-adapter/index.ts
  packages/@o3r/extractors/schematics/cms-adapter/templates/placeholders.metadata.json
  packages/@o3r/extractors/schematics/cms-adapter/templates/tsconfig.cms.json
  packages/@o3r/extractors/schematics/ng-add/index.ts
  packages/@o3r/localization/schematics/cms-adapter/index.ts
  packages/@o3r/localization/schematics/localization-base/index.ts
  packages/@o3r/localization/schematics/ng-add/index.ts
  packages/@o3r/rules-engine/package.json
  packages/@o3r/rules-engine/schematics/cms-adapter/index.ts
  packages/@o3r/rules-engine/schematics/ng-add/index.ts
  packages/@o3r/rules-engine/schematics/ng-add/schema.json
  packages/@o3r/rules-engine/schematics/ng-add/schema.ts
  packages/@o3r/schematics/src/utility/collection.ts
  packages/@o3r/styling/package.json
  packages/@o3r/styling/schematics/cms-adapter/index.ts
  packages/@o3r/styling/schematics/ng-add/index.ts
  packages/@o3r/styling/schematics/ng-add/schema.json
  packages/@o3r/styling/schematics/ng-add/schema.ts
  yarn.lock
Labels: enhancement

#577 fix: rollback to initial cascading strategy to avoid wrong conflict resolution
  apps/github-cascading-app/schemas/config.schema.json
  apps/github-cascading-app/src/cascading/cascading-probot.ts
  apps/github-cascading-app/src/cascading/cascading.spec.ts
  apps/github-cascading-app/src/cascading/cascading.ts
  apps/github-cascading-app/src/cascading/interfaces.ts
Labels: bug

#562 o3r create workspace
  packages/@o3r/core/package.json
  packages/@o3r/core/schematics/ng-add/project-setup/index.ts
  packages/@o3r/core/schematics/rule-factories/additional-modules/index.ts
  packages/@o3r/core/schematics/rule-factories/index.ts
  packages/@o3r/core/schematics/rule-factories/monorepo/index.ts
  packages/@o3r/core/schematics/rule-factories/o3r-basic-updates/index.ts
  packages/@o3r/core/schematics/rule-factories/otter-environment/index.ts
  packages/@o3r/core/schematics/rule-factories/store/index.ts
  packages/@o3r/core/schematics/shared/presets/basic.preset.ts
  packages/@o3r/core/schematics/shared/presets/cms.preset.ts
  packages/@o3r/core/schematics/shared/presets/helpers.ts
  packages/@o3r/create/src/index.ts
  packages/@o3r/schematics/src/index.spec.ts
  packages/@o3r/schematics/src/interfaces/angular-workspace.ts
  packages/@o3r/schematics/src/utility/collection.spec.ts
  packages/@o3r/schematics/src/utility/collection.ts
  packages/@o3r/schematics/src/utility/monorepo.ts
  yarn.lock
Labels: enhancement

#598 fix: do nothing when presets modules list is empty
  packages/@o3r/core/schematics/shared/presets/helpers.ts
Labels: bug

#600 fix: vscode extension display name
  apps/vscode-extension/package.json
Labels: bug

#593 feat: upgrade to angular 16.1
  .github/workflows/code-check.yml
  .yarnrc.yml
  apps/chrome-devtools/package.json
  apps/github-cascading-app/package.json
  apps/vscode-extension/package.json
  package.json
  packages/@ama-sdk/core/package.json
  packages/@ama-sdk/create/package.json
  packages/@ama-sdk/generator-sdk/package.json
  packages/@ama-sdk/generator-sdk/src/generators/shell/templates/base/package.json
  packages/@ama-sdk/schematics/package.json
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/package.json.template
  packages/@ama-sdk/swagger-builder/package.json
  packages/@ama-terasu/cli/package.json
  packages/@ama-terasu/core/package.json
  packages/@ama-terasu/schematics/package.json
  packages/@o3r/amaterasu/amaterasu-api-spec/package.json
  packages/@o3r/amaterasu/amaterasu-dodo/package.json
  packages/@o3r/amaterasu/amaterasu-otter/package.json
  packages/@o3r/amaterasu/amaterasu-sdk/package.json
  packages/@o3r/analytics/package.json
  packages/@o3r/apis-manager/package.json
  packages/@o3r/application/package.json
  packages/@o3r/components/package.json
  packages/@o3r/configuration/package.json
  packages/@o3r/core/package.json
  packages/@o3r/create/package.json
  packages/@o3r/dev-tools/package.json
  packages/@o3r/dynamic-content/package.json
  packages/@o3r/eslint-config-otter/package.json
  packages/@o3r/eslint-plugin/package.json
  packages/@o3r/extractors/package.json
  packages/@o3r/forms/package.json
  packages/@o3r/localization/package.json
  packages/@o3r/logger/package.json
  packages/@o3r/mobile/package.json
  packages/@o3r/routing/package.json
  packages/@o3r/rules-engine/package.json
  packages/@o3r/schematics/package.json
  packages/@o3r/store-sync/package.json
  packages/@o3r/storybook/package.json
  packages/@o3r/stylelint-plugin/package.json
  packages/@o3r/styling/package.json
  packages/@o3r/testing/package.json
  packages/@o3r/third-party/package.json
  tools/@o3r/build-helpers/package.json
  tools/github-actions/audit/package.json
  tools/github-actions/cascading/package.json
  tools/github-actions/get-npm-tag/package.json
  tools/github-actions/new-version/package.json
  yarn.lock
Labels: enhancement

#604 docs: change readme title for initializer package
  packages/@ama-sdk/create/README.md
  packages/@o3r/create/README.md
Labels: documentation
