Repository AmadeusITGroup/otter, pull requests merged in 2023-04, with the labels that each got.

#277 feat: changelog enhancement
  .commitlintrc.json
  .github/release.yml
  .github/workflows/pr-labels.yml
  CONTRIBUTING.md
  tools/@o3r/build-helpers/package.json
  tools/@o3r/build-helpers/scripts/pr-labels.mjs
  yarn.lock
Labels: enhancement

#278 chore: fix new logo ratio on published documentation
  CONTRIBUTING.md
  README.md
Labels: documentation

#279 fix: border of the logo for 300dpi png
  .attachments/logos/otter-a-bg.png
  .attachments/logos/otter-a-with-text-bg.png
  .attachments/logos/otter-a-with-text.png
  .attachments/logos/otter-a.png
  .attachments/logos/otter-alone.png
  .attachments/logos/otter-fork-me.png
  .attachments/otter.png
  .attachments/otter.svg
Labels: bug

#283 fix: remove auto generated azure pipeline
  .github/workflows/main_github-cascading.yml
Labels: bug

#276 fix: generators templates
  packages/@o3r/core/schematics/module/templates/base/ng-package.json.template
Labels: bug

#266 feat: 1448 apply user animation preference on otter generated application
  docs/application/REDUCED_MOTION.md
  docs/core/START_NEW_APPLICATION.md
  packages/@o3r/apis-manager/schematics/helpers/update-api-deps/index.ts
  packages/@o3r/application/package.json
  packages/@o3r/application/schematics/ng-add/index.ts
  packages/@o3r/application/src/browser-preference/helper.ts
  packages/@o3r/application/src/browser-preference/index.ts
  packages/@o3r/application/src/public_api.ts
  packages/@o3r/core/package.json
  packages/@o3r/core/schematics/ng-add/index.ts
  packages/@o3r/core/schematics/rule-factories/additional-modules/index.ts
  packages/@o3r/core/schematics/rule-factories/customization-environment/index.ts
  packages/@o3r/core/schematics/rule-factories/store/index.ts
  packages/@o3r/localization/schematics/localization-base/index.ts
  packages/@o3r/schematics/src/rule-factories/ng-add/index.ts
  packages/@o3r/schematics/src/utility/modules.ts
  yarn.lock
Labels: enhancement

#287 fix: pull request label caculation
  .github/workflows/pr-labels.yml
Labels: bug

#285 feat: add sticker logo
  .attachments/logos/sticker.png
  .attachments/otter.svg
  .husky/commit-msg
  .husky/pre-commit
Labels: enhancement

#289 fix: bump ngrx to be include in renovate auto update
  apps/chrome-devtools/package.json
  packages/@o3r/analytics/package.json
  packages/@o3r/components/package.json
  packages/@o3r/configuration/package.json
  packages/@o3r/core/package.json
  packages/@o3r/dynamic-content/package.json
  packages/@o3r/forms/package.json
  packages/@o3r/localization/package.json
  packages/@o3r/logger/package.json
  packages/@o3r/mobile/package.json
  packages/@o3r/routing/package.json
  packages/@o3r/rules-engine/package.json
  packages/@o3r/storybook/package.json
  packages/@o3r/testing/package.json
  yarn.lock
Labels: bug

#291 fix: generate request metadata default value to in SDK
  packages/@ama-sdk/generator-sdk/src/generators/core/templates/swagger-codegen-typescript/src/main/resources/typescriptFetch/api/api.mustache
Labels: bug

#292 feat: support external nested config
  packages/@o3r/components/builders/component-extractor/helpers/component/component-config.extractor.ts
  packages/@o3r/components/builders/component-extractor/helpers/component/component.extractor.ts
  packages/@o3r/components/builders/component-extractor/helpers/component/component.parser.ts
  packages/@o3r/components/builders/component-extractor/index.ts
Labels: enhancement
