Repository AmadeusITGroup/otter, pull requests merged in 2023-08, with the labels that each got.

#606 feat: improve schematic ux by proposing to run schematic when the main failed for a known reason
  packages/@o3r/analytics/schematics/analytics-to-component/index.spec.ts
  packages/@o3r/analytics/schematics/analytics-to-component/index.ts
  packages/@o3r/configuration/schematics/configuration-to-component/index.spec.ts
  packages/@o3r/configuration/schematics/configuration-to-component/index.ts
  packages/@o3r/core/package.json
  packages/@o3r/core/schematics/context-to-component/index.spec.ts
  packages/@o3r/core/schematics/context-to-component/index.ts
  packages/@o3r/localization/package.json
  packages/@o3r/localization/schematics/add-localization-key/index.spec.ts
  packages/@o3r/localization/schematics/add-localization-key/index.ts
  packages/@o3r/localization/schematics/localization-to-component/index.spec.ts
  packages/@o3r/localization/schematics/localization-to-component/index.ts
  packages/@o3r/schematics/src/utility/component.ts
  packages/@o3r/testing/package.json
  packages/@o3r/testing/schematics/fixture-to-component/index.spec.ts
  packages/@o3r/testing/schematics/fixture-to-component/index.ts
  packages/@o3r/third-party/package.json
  packages/@o3r/third-party/schematics/iframe-to-component/index.spec.ts
  packages/@o3r/third-party/schematics/iframe-to-component/index.ts
  yarn.lock
Labels: enhancement

#617 fix: setup of @o3r/localization schematics
  packages/@o3r/localization/schematics/ng-add/index.ts
Labels: bug

#614 fix: question to change localization key name
  packages/@o3r/localization/schematics/add-localization-key/index.spec.ts
  packages/@o3r/localization/schematics/add-localization-key/index.ts
  packages/@o3r/schematics/src/utility/index.ts
  packages/@o3r/schematics/src/utility/question.ts
Labels: bug

#622 fix: remove useless release workflow
  .github/workflows/release.yml
Labels: bug

#620 fix: disable nx cloud for release branches
  .github/workflows/code-check.yml
  .github/workflows/main.yml
  .github/workflows/publish.yml
  .github/workflows/test-publish.yml
Labels: bug

#629 fix: github ref branch name format
  .github/workflows/main.yml
Labels: bug

#616 fix: use schematic context to retrieve its name
  packages/@ama-sdk/generator-sdk/src/generators/shell/templates/base/package.json
  packages/@o3r/core/schematics/library/index.ts
  packages/@o3r/core/schematics/sdk/index.ts
  packages/@o3r/schematics/src/utility/collection.spec.ts
  packages/@o3r/schematics/src/utility/collection.ts
  packages/@o3r/schematics/src/utility/monorepo.ts
Labels: bug

#632 fix: sdk generator - missing export in base shell
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/helpers/index.ts
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/models/base/enums.ts
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/models/base/patterns.ts
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/models/core/patterns.ts
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/models/custom/enums.ts
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/models/custom/patterns.ts
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/spec/api-mock.ts
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/spec/mock-factory/index.ts
  packages/@ama-sdk/schematics/schematics/typescript/shell/templates/base/src/spec/operation-adapter.ts
Labels: bug

#641 fix: missing status code response when multiple response with same type
  packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/java/com/amadeus/codegen/ts/AbstractTypeScriptClientCodegen.java
  packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/api/api.mustache
  packages/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/src/main/resources/typescriptFetch/api/fixture.jest.mustache
  packages/@ama-sdk/schematics/testing/MOCK_swagger.yaml
Labels: bug

#648 fix: null pointer on this in storage sync
  packages/@o3r/store-sync/src/core/storage-sync.ts
Labels: bug

#642 feat(vscode ext): support of new generators
  apps/vscode-extension/package.json
  apps/vscode-extension/src/commands/generate/enrich-component/analytics-to-component.commands.ts
  apps/vscode-extension/src/commands/generate/enrich-component/common.ts
  apps/vscode-extension/src/commands/generate/enrich-component/configuration-to-component.commands.ts
  apps/vscode-extension/src/commands/generate/enrich-component/context-to-component.commands.ts
  apps/vscode-extension/src/commands/generate/enrich-component/convert-component.commands.ts
  apps/vscode-extension/src/commands/generate/enrich-component/fixture-to-component.commands.ts
  apps/vscode-extension/src/commands/generate/enrich-component/iframe-to-component.commands.ts
  apps/vscode-extension/src/commands/generate/enrich-component/index.ts
  apps/vscode-extension/src/commands/generate/enrich-component/localization-to-component.commands.ts
  apps/vscode-extension/src/commands/generate/enrich-component/rules-engine-to-component.commands.ts
  apps/vscode-extension/src/commands/generate/enrich-component/theming-to-component.commands.ts
  apps/vscode-extension/src/extension.ts
Labels: enhancement

#613 feat: ng add @o3r/testing independent from @o3rcore
  packages/@o3r/core/package.json
  packages/@o3r/core/schematics/ng-add/project-setup/index.ts
  packages/@o3r/core/schematics/ng-add/schema.json
  packages/@o3r/core/schematics/ng-add/schema.ts
  packages/@o3r/core/schematics/rule-factories/index.ts
  packages/@o3r/core/schematics/service/index.ts
  packages/@o3r/schematics/src/interfaces/angular-workspace.ts
  packages/@o3r/schematics/src/rule-factories/get-test-frameworks/index.ts
  packages/@o3r/schematics/src/rule-factories/index.ts
  packages/@o3r/schematics/src/utility/collection.spec.ts
  packages/@o3r/testing/package.json
  packages/@o3r/testing/schematics/ng-add/fixture/index.ts
  packages/@o3r/testing/schematics/ng-add/index.ts
  packages/@o3r/testing/schematics/ng-add/schema.json
  packages/@o3r/testing/schematics/ng-add/schema.ts
  packages/@o3r/testing/schematics/ng-add/templates/project/jest.config.js.template
  packages/@o3r/testing/schematics/ng-add/templates/project/testing/setup-jest.ts.template
  packages/@o3r/testing/schematics/ng-add/templates/workspace/jest.config.js.template
  yarn.lock
Labels: enhancement

#659 feat(vscode ext): use schematic options from angular.json or nx.json
  apps/vscode-extension/package.json
  apps/vscode-extension/src/commands/extract/styling/helpers/utils.helper.ts
  apps/vscode-extension/src/commands/generate/component.command.ts
  apps/vscode-extension/src/commands/generate/enrich-component/analytics-to-component.commands.ts
  apps/vscode-extension/src/commands/generate/enrich-component/common.ts
  apps/vscode-extension/src/commands/generate/enrich-component/localization-to-component.commands.ts
  apps/vscode-extension/src/commands/generate/fixture.command.ts
  apps/vscode-extension/src/commands/generate/module.command.ts
  apps/vscode-extension/src/commands/generate/service.command.ts
  apps/vscode-extension/src/commands/generate/store.command.ts
  apps/vscode-extension/src/commands/helpers.ts
  apps/vscode-extension/src/commands/module/add-module.command.ts
Labels: enhancement

#662 fix: fallback on missing status code from API response
  packages/@ama-sdk/core/src/fwk/api.helper.spec.ts
  packages/@ama-sdk/core/src/fwk/api.helpers.ts
  packages/@ama-sdk/core/src/fwk/clients/api-beacon-client.ts
  packages/@ama-sdk/core/src/fwk/clients/api-fetch-client.ts
  packages/@ama-sdk/core/src/fwk/core/api-client.ts
  packages/@ama-sdk/core/src/fwk/core/base-api-constructor.ts
Labels: bug

#664 fix: add yarn.lock in NX global watch list
  nx.json
Labels: bug

#663 feat: playwright install part of o3r/testing
  packages/@ama-sdk/core/package.json
  packages/@ama-sdk/schematics/package.json
  packages/@o3r/core/schematics/ng-add/project-setup/index.ts
  packages/@o3r/core/schematics/ng-add/schema.json
  packages/@o3r/core/schematics/ng-add/schema.ts
  packages/@o3r/testing/schematics/ng-add/index.ts
  packages/@o3r/testing/schematics/ng-add/playwright/index.ts
  packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/playwright-config.sanity.ts.template
  packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/playwright-config.ts.template
  packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/sanity/__sanity@dasherize__.e2e.ts
  packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/scenarios/__name@dasherize__.e2e-playwright-spec.ts
  packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/utils/base-scenario.ts
  packages/@o3r/testing/schematics/ng-add/playwright/templates/e2e-playwright/utils/index.ts
  packages/@o3r/testing/schematics/ng-add/schema.json
  packages/@o3r/testing/schematics/ng-add/schema.ts
  yarn.lock
Labels: enhancement

#675 fix: add missing routing module in the page module
  packages/@o3r/core/schematics/page/index.spec.ts
  packages/@o3r/core/schematics/page/index.ts
Labels: bug

#673 fix: cleanup unused screenshots
  .attachments/custo-img/add-custo-tooling-trigger.png
  .attachments/custo-img/add-pipeline-trigger.png
  .attachments/custo-img/branch-menu.png
  .attachments/custo-img/branches.png
  .attachments/custo-img/build-policy-config.png
  .attachments/custo-img/build-policy.png
  .attachments/custo-img/create-custo-repo-2.png
  .attachments/custo-img/create-custo-repo.png
  .attachments/custo-img/create-pipeline.png
  .attachments/custo-img/create-upgrade-pipeline.png
  .attachments/custo-img/git-pipeline.png
  .attachments/custo-img/grant-permission.png
  .attachments/custo-img/keys.png
  .attachments/custo-img/new-upgrade-pipeline.png
  .attachments/custo-img/pipeline.png
  .attachments/custo-img/repo-selection.png
  .attachments/custo-img/review-pipeline.png
  .attachments/custo-img/run-pipeline.png
  .attachments/custo-img/schedule-frq.png
  .attachments/custo-img/schedule-run.png
  .attachments/custo-img/yaml-selection.png
Labels: bug

#688 fix: legacy SDK generation for Windows
  packages/@ama-sdk/generator-sdk/src/generators/core/index.ts
  packages/@o3r/core/package.json
Labels: bug

#695 docs: equals operator typo
  docs/rules-engine/examples/runtime-facts.md
  docs/rules-engine/how-it-works/operators.md
  docs/rules-engine/how-it-works/rule.md
  docs/rules-engine/how-it-works/ruleset.md
  docs/rules-engine/operators.md
  docs/rules-engine/rule.md
  docs/rules-engine/ruleset.md
Labels: documentation

#696 fix: documentation readme link of Ama-terasu generator
  packages/@ama-sdk/generator-sdk/src/generators/shell/templates/base/package.json
  packages/@ama-terasu/schematics/README.md
Labels: bug, documentation

#699 docs: fix title in core readme
  packages/@o3r/core/README.md
Labels: documentation

#658 feat: do not synchronize untouched state with the localstorage [perf]
  packages/@o3r/mobile/package.json
  packages/@o3r/store-sync/package.json
  packages/@o3r/store-sync/src/core/interfaces.ts
  packages/@o3r/store-sync/src/core/storage-sync.ts
  packages/@o3r/store-sync/src/sync-storage/interfaces.ts
  packages/@o3r/store-sync/src/sync-storage/storage-sync.ts
  packages/@o3r/store-sync/tsconfig.build.json
  yarn.lock
Labels: enhancement

#700 fix: remove references to nonexisting migration scripts
  packages/@o3r/core/migration.json
  packages/@o3r/core/schematics/ng-update/index.ts
  packages/@o3r/core/schematics/ng-update/v4.2/store-reducer-interface.ts
  packages/@o3r/core/schematics/ng-update/v4.3/material-theme-cssvar.ts
  packages/@o3r/core/schematics/ng-update/v4.3/playwright-update.ts
  packages/@o3r/core/schematics/ng-update/v4.4/typographies-cssvar.ts
  packages/@o3r/core/schematics/ng-update/v4/api-services/index.ts
  packages/@o3r/core/schematics/ng-update/v4/store-actions/exported-actions-v3.json
  packages/@o3r/core/schematics/ng-update/v4/store-actions/index.ts
  packages/@o3r/core/schematics/ng-update/v4/sub-entries/index.ts
  packages/@o3r/core/schematics/ng-update/v4/sub-entries/mapping-from-v3.json
  packages/@o3r/core/schematics/ng-update/v5.0/fixture-import.ts
  packages/@o3r/core/schematics/ng-update/v6.1/mocks/angular.app.mocks.json
  packages/@o3r/core/schematics/ng-update/v6.1/mocks/app.index.ts.mock
  packages/@o3r/core/schematics/ng-update/v6.1/mocks/expected.app.index.ts.mock
  packages/@o3r/core/schematics/ng-update/v6.1/mocks/package.mocks.json
  packages/@o3r/core/schematics/ng-update/v6.1/remove-ponyfill.spec.ts
  packages/@o3r/core/schematics/ng-update/v6.1/remove-ponyfill.ts
  packages/@o3r/core/schematics/ng-update/v6.1/use-ngx-prefetch.spec.ts
  packages/@o3r/core/schematics/ng-update/v6.1/use-ngx-prefetch.ts
  packages/@o3r/core/schematics/ng-update/v6.3/mocks/.renovaterc.json
  packages/@o3r/core/schematics/ng-update/v6.3/mocks/expected.renovaterc.json
  packages/@o3r/core/schematics/ng-update/v6.3/update-renovate-config.spec.ts
  packages/@o3r/core/schematics/ng-update/v6.3/update-renovate-config.ts
  packages/@o3r/core/schematics/ng-update/v6/angular.app.mocks.json
  packages/@o3r/core/schematics/ng-update/v6/angular.lib.mocks.json
  packages/@o3r/core/schematics/ng-update/v6/update-angular-json.spec.ts
  packages/@o3r/core/schematics/ng-update/v6/update-angular-json.ts
  packages/@o3r/core/schematics/ng-update/v7.0/mocks/angular.app.mocks.json
  packages/@o3r/core/schematics/ng-update/v7.0/mocks/package.mocks.json
  packages/@o3r/core/schematics/ng-update/v7.0/mocks/package.mocks.result.json
  packages/@o3r/core/schematics/ng-update/v7.0/update-localization-generation.spec.ts
  packages/@o3r/core/schematics/ng-update/v7.0/update-localization-generation.ts
Labels: bug

#697 feat: add project label
  .github/.pr-labelrc.json
  .github/release.yml
  .github/workflows/pr-labels.yml
  apps/chrome-devtools/project.json
  nx.json
  packages/@ama-sdk/core/project.json
  tools/@o3r/build-helpers/project.json
  tools/@o3r/build-helpers/schemas/pr-labels.configuration.schema.json
  tools/@o3r/build-helpers/scripts/pr-labels.mjs
Labels: enhancement, project:@o3r/chrome-devtools, project:@ama-sdk/core, project:@o3r/build-helpers

#706 ci: tag unit tests on windows as experimental to prevent blocking the…
  .github/workflows/code-check.yml
Labels: enhancement

#705 feat: Update JSON schema (config) for widget configuration + required field
  packages/@o3r/configuration/schemas/configuration.metadata.schema.json
Labels: enhancement, project:@o3r/configuration

#633 feat: ng add of packages will run depending of project type
  packages/@o3r/apis-manager/schematics/ng-add/index.ts
  packages/@o3r/application/schematics/ng-add/index.ts
  packages/@o3r/components/schematics/ng-add/index.ts
  packages/@o3r/configuration/schematics/ng-add/index.ts
  packages/@o3r/core/schematics/ng-add/project-setup/index.ts
  packages/@o3r/core/schematics/ng-add/schema.json
  packages/@o3r/core/schematics/ng-add/schema.ts
  packages/@o3r/core/schematics/rule-factories/additional-modules/index.ts
  packages/@o3r/core/schematics/rule-factories/customization-environment/index.ts
  packages/@o3r/core/schematics/rule-factories/o3r-basic-updates/index.ts
  packages/@o3r/core/schematics/rule-factories/otter-environment/index.ts
  packages/@o3r/core/schematics/rule-factories/playwright/index.ts
  packages/@o3r/core/schematics/rule-factories/store/index.ts
  packages/@o3r/eslint-config-otter/schematics/ng-add/index.ts
  packages/@o3r/extractors/schematics/ng-add/index.ts
  packages/@o3r/localization/schematics/localization-base/index.ts
  packages/@o3r/localization/schematics/ng-add/index.ts
  packages/@o3r/mobile/schematics/ng-add/index.ts
  packages/@o3r/rules-engine/schematics/ng-add/index.ts
  packages/@o3r/schematics/src/rule-factories/ng-add/index.ts
  packages/@o3r/schematics/src/tasks/ng-add/index.ts
  packages/@o3r/schematics/src/utility/loaders.ts
  packages/@o3r/schematics/src/utility/modules.ts
  packages/@o3r/store-sync/schematics/ng-add/index.ts
  packages/@o3r/storybook/schematics/ng-add/index.ts
  packages/@o3r/styling/schematics/ng-add/index.ts
  packages/@o3r/testing/schematics/ng-add/index.ts
  packages/@o3r/testing/schematics/ng-add/playwright/index.ts
Labels: enhancement
