Repository AmadeusITGroup/otter, pull requests merged in 2023-05, with the labels that each got.

#301 feat: add code analysis
  .github/workflows/codeql.yml
Labels: enhancement

#320 feat: add release/*-next branches in the Renovate update rules
  .renovaterc.json
Labels: enhancement

#316 fix: avoid error when not log history in -1
  .github/workflows/pr-labels.yml
  tools/@o3r/build-helpers/scripts/pr-labels.mjs
Labels: bug

#315 feat: add official module indicator
  packages/@ama-terasu/cli/src/helpers/module.helper.ts
  packages/@ama-terasu/cli/src/helpers/version.helper.ts
Labels: enhancement

#330 fix: codeql high suggestions
  apps/vscode-extension/src/commands/extract/styling/helpers/regex.helper.ts
  apps/vscode-extension/src/commands/extract/styling/helpers/utils.helper.ts
  packages/@o3r/dev-tools/src/cli/package-export.ts
  packages/@o3r/dev-tools/src/cli/set-version.ts
  packages/@o3r/rules-engine/src/components/rules-engine/rule-condition/rule-condition-pres.component.ts
  packages/@o3r/schematics/src/utility/gitignore.ts
  packages/@o3r/schematics/src/utility/template-property.helper.ts
  packages/@o3r/storybook/addon/theme.tsx
  packages/@o3r/styling/builders/style-extractor/helpers/css-variable.extractor.ts
Labels: bug

#329 fix: ignore generated JS from code scanning
  .github/codeql/codeql-config.yml
  .github/workflows/codeql.yml
Labels: bug

#326 feat: auto update the dependencies and package manager versions
  .renovaterc.json
  package.json
  packages/@ama-sdk/generator-sdk/src/generators/shell/templates/base/package.json
  packages/@o3r/dev-tools/src/cli/version-harmonize.ts
  packages/@o3r/dev-tools/src/helpers/version-harmonize/interfaces.ts
  scripts/yarn-harmonize.js
Labels: enhancement

#294 fix: throwOnUndefined to work with playwrigh
  packages/@ama-sdk/core/schematics/ng-add/mocks/angular.mocks.json
  packages/@ama-sdk/generator-sdk/collection.json
  packages/@o3r/components/builders.json
  packages/@o3r/components/testing/mocks/angular.mocks.json
  packages/@o3r/core/builders.json
  packages/@o3r/core/collection.json
  packages/@o3r/core/migration.json
  packages/@o3r/core/package.json
  packages/@o3r/core/schematics/fixture/helpers.ts
  packages/@o3r/core/testing/mocks/angular.mocks.json
  packages/@o3r/localization/builders.json
  packages/@o3r/rules-engine/builders.json
  packages/@o3r/schematics/src/utility/loaders.ts
  packages/@o3r/styling/builders.json
  packages/@o3r/styling/collection.json
  packages/@o3r/testing/migration.json
  packages/@o3r/testing/schematics/ng-update/v9-0/index.ts
  packages/@o3r/testing/schematics/ng-update/v9-0/throw-on-undefined/mocks/angular.mocks.json.template
  packages/@o3r/testing/schematics/ng-update/v9-0/throw-on-undefined/mocks/fixture.mocks.result.ts.template
  packages/@o3r/testing/schematics/ng-update/v9-0/throw-on-undefined/mocks/fixture.mocks.ts.template
  packages/@o3r/testing/schematics/ng-update/v9-0/throw-on-undefined/throw-on-undefined.spec.ts
  packages/@o3r/testing/schematics/ng-update/v9-0/throw-on-undefined/throw-on-undefined.ts
  packages/@o3r/testing/src/core/angular/component-fixture.ts
  packages/@o3r/testing/src/core/component-fixture.ts
  packages/@o3r/testing/src/core/helpers.ts
  packages/@o3r/testing/src/core/playwright/component-fixture.ts
  packages/@o3r/testing/src/core/protractor/component-fixture.ts
  packages/@o3r/testing/testing/mocks/angular.mocks.json
  packages/@o3r/testing/tsconfig.json
Labels: bug, enhancement

#274 feat: cascading application
  .attachments/logos/otter-cascading.png
  .attachments/otter.svg
  .github/.cascadingrc.json
  .github/workflows/main.yml
  .github/workflows/publish.yml
  .gitignore
  .yarnrc.yml
  apps/github-cascading-app/.eslintrc.js
  apps/github-cascading-app/.gitignore
  apps/github-cascading-app/README.md
  apps/github-cascading-app/app.yml
  apps/github-cascading-app/function.json
  apps/github-cascading-app/jest.config.js
  apps/github-cascading-app/package.json
  apps/github-cascading-app/project.json
  apps/github-cascading-app/schemas/config.schema.json
  apps/github-cascading-app/scripts/prepare-azure-function.mjs
  apps/github-cascading-app/src/app.ts
  apps/github-cascading-app/src/cascading/cascading-probot.ts
  apps/github-cascading-app/src/cascading/cascading.spec.ts
  apps/github-cascading-app/src/cascading/cascading.ts
  apps/github-cascading-app/src/cascading/interfaces.ts
  apps/github-cascading-app/src/github-cascading/index.ts
  apps/github-cascading-app/testing/setup-jest.ts
  apps/github-cascading-app/tsconfig.build.json
  apps/github-cascading-app/tsconfig.eslint.json
  apps/github-cascading-app/tsconfig.json
  apps/github-cascading-app/tsconfig.spec.json
  tools/github-actions/audit/readme.md
  tools/github-actions/cascading/readme.md
  tools/github-actions/cascading/src/helpers.ts
  tools/github-actions/download-build-output/readme.md
  tools/github-actions/get-npm-tag/readme.md
  tools/github-actions/new-version/readme.md
  tools/github-actions/setup/readme.md
  tools/github-actions/upload-build-output/readme.md
  tsconfig.base.json
  tsconfig.jest.json
  yarn.lock
Labels: enhancement

#333 fix: add build dependency to eslint-config
  packages/@o3r/eslint-config-otter/project.json
Labels: bug

#338 fix: version-harmonize apply-to path delimiter
  .gitattributes
  .stylelintrc.json
  .yarn/sdks/integrations.yml
  GitVersion.yml
  LICENSE
  packages/@o3r/dev-tools/src/cli/version-harmonize.ts
Labels: bug

#317 fix(core): documentation of the ng add
  README.md
  docs/core/START_NEW_APPLICATION.md
  packages/@o3r/core/schematics/ng-add/schema.json
Labels: bug, documentation

#343 fix: remove the dependency of schematics to dev-tools
  packages/@o3r/dev-tools/src/utils/check-peer-deps.ts
  packages/@o3r/schematics/package.json
  packages/@o3r/schematics/src/rule-factories/check-packages-peers/index.ts
Labels: bug

#341 fix: parsing of the cascading app config
  .eslintrc.js
  .husky/commit-msg
  .husky/pre-commit
  apps/github-cascading-app/src/cascading/cascading-probot.ts
Labels: bug

#348 doc: enhance CONTRIBUTING.md guidelines
  CONTRIBUTING.md
Labels: documentation

#350 feat: remove github cache
  .github/workflows/audit.yml
  .github/workflows/code-check.yml
  .github/workflows/main.yml
  .github/workflows/pr-labels.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/test-publish.yml
  tools/github-actions/setup/action.yml
  tools/github-actions/setup/readme.md
Labels: enhancement

#349 fix: resolve new package with fs instead of node resolver
  packages/@ama-terasu/cli/src/helpers/module.helper.ts
  packages/@ama-terasu/cli/src/helpers/version.helper.ts
  packages/@ama-terasu/cli/src/modules/base-yargs.ts
Labels: bug

#345 feat: add useless custom Otter logo
  .attachments/logos/afrotter.png
  .attachments/logos/otter-business.png
  .attachments/logos/otter-straw-hat.png
  .attachments/otter.png
  .attachments/otter.svg
Labels: enhancement

#351 fix: ng-add run with npm - missing dependencies
  packages/@o3r/schematics/schematics/ng-add/index.ts
Labels: bug

#354 fix: install correct angular-devkit/architect on ng-add
  packages/@o3r/schematics/package.json
  yarn.lock
Labels: bug

#356 fix: add missing ng-update to core
  packages/@o3r/core/migration.json
Labels: bug

#360 feat: add otter schematics collection to ngCli at ngAdd time
  packages/@o3r/components/schematics/ng-add/index.ts
  packages/@o3r/core/schematics/ng-add/index.ts
  packages/@o3r/schematics/src/rule-factories/ng-add/index.ts
  packages/@o3r/schematics/src/utility/collection.ts
  packages/@o3r/schematics/src/utility/index.ts
  packages/@o3r/schematics/src/utility/loaders.ts
  packages/@o3r/testing/schematics/ng-add/index.ts
Labels: enhancement

#366 fix: add missing ng-update to core
  packages/@o3r/core/migration.json
Labels: bug

#365 feat: add the capability to not provide callback to effect helpers
  packages/@o3r/core/src/store/async/async.operators.ts
Labels: enhancement

#369 fix: playwright integration
  packages/@o3r/core/schematics/module/templates/base/package.json.template
  packages/@o3r/core/schematics/rule-factories/playwright/index.ts
  packages/@o3r/testing/package.json
  packages/@o3r/testing/src/core/playwright/element.ts
  yarn.lock
Labels: bug

#370 fix: set playwright as peer-dep
  .github/workflows/test-publish.yml
  packages/@o3r/core/schematics/index.it.spec.ts
  packages/@o3r/testing/package.json
  yarn.lock
Labels: bug
