Repository AmadeusITGroup/otter, pull requests merged in 2025-10, with the labels that each got.

#3564 feat(vscode): use available tools linked to otter or angular to reply
  apps/vscode-extension/package.json
  apps/vscode-extension/src/chat/index.ts
  apps/vscode-extension/src/extension.ts
  yarn.lock
Labels: enhancement, project:otter-devtools

#3559 fix: apply eslint config on generated application with @o3r/testing
  packages/@o3r/core/schematics/ng-add-create/templates/schematics/ng-add/index.ts.template
  packages/@o3r/eslint-config/schematics/ng-add/eslint/index.spec.ts
  packages/@o3r/eslint-config/schematics/ng-add/eslint/index.ts
  packages/@o3r/eslint-config/schematics/ng-add/eslint/templates/project/eslint.local.config.__extension__.template
  packages/@o3r/eslint-config/schematics/ng-add/schema.json
  packages/@o3r/eslint-config/src/rules/typescript.cjs
  packages/@o3r/testing/package.json
  packages/@o3r/testing/schematics/index.it.spec.ts
  packages/@o3r/testing/schematics/ng-add/index.ts
  packages/@o3r/testing/schematics/ng-add/jest/index.ts
  packages/@o3r/testing/schematics/ng-add/jest/templates/project/jest.config.js.template
  packages/@o3r/testing/schematics/ng-add/jest/templates/project/testing/setup-jest.ts.template
  packages/@o3r/testing/schematics/ng-add/jest/templates/workspace/jest.config.js.template
  packages/@o3r/testing/schematics/ng-add/jest/templates/workspace/jest.config.ut.js.template
  packages/@o3r/testing/schematics/ng-add/jest/templates/workspace/tsconfig.jest.json.template
  packages/@o3r/testing/schematics/ng-add/playwright/index.ts
  packages/@o3r/workspace/schematics/library/templates/ng/common/tsconfig.json.template
  packages/@o3r/workspace/schematics/ng-add/helpers/npm-workspace.ts
  packages/@o3r/workspace/schematics/ng-add/project-setup.ts
  yarn.lock
Labels: bug, project:@o3r/core, project:@o3r/testing, project:@o3r/workspace, project:audit-gh-action, project:get-npm-tag-gh-action, project:new-version-gh-action, project:@o3r/eslint-config, project:release-gh-action, project:yarn-errors-reporter-gh-action, runAllTests

#3581 fix: increase operations limit for stale issue workflow
  .github/workflows/stale-issue-pr.yml
Labels: bug
